version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8081:8080" # Mapea el puerto 8081 del host al puerto 8080 del contenedor
    environment:
      - HOST=db
      - USER=postgres
      - PASSWORD=admin
      - DATABASE=users
      - PORT=5432
    depends_on:
      - db
    volumes:
      - .:/app # Mapea el directorio actual en el directorio /app dentro del contenedor

  db:
    image: postgres:latest
    ports:
      - "5433:5432" # Mapea el puerto 5433 del host al puerto 5432 del contenedor
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=users
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persiste los datos de postgres

volumes:
  postgres_data: # Define un volumen para la persistencia de datos de PostgreSQL
